# Generated by Django 3.2.7 on 2021-09-27 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField()),
                ('name', models.TextField()),
                ('starch', models.PositiveSmallIntegerField()),
                ('fruit', models.PositiveSmallIntegerField()),
                ('dairy', models.PositiveSmallIntegerField()),
                ('vegetable', models.PositiveSmallIntegerField()),
                ('protein', models.PositiveSmallIntegerField()),
                ('fat', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
