# Generated by Django 3.2.7 on 2021-09-28 01:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_plan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
